/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */

export * from './authResponseDto';
export * from './createMessageDto';
export * from './createTagDto';
export * from './healthResponseDto';
export * from './loginDto';
export * from './messageAuthorDto';
export * from './messageControllerFindAllParams';
export * from './messageResponseDto';
export * from './messageTagDto';
export * from './paginatedMessagesResponseDto';
export * from './registerDto';
export * from './tagResponseDto';
export * from './updateMessageDto';
export * from './userResponseDto';
