/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */

export type MessageControllerFindAllParams = {
  /**
   * Filter by tag ID
   */
  tagId?: string;
  /**
   * Filter by author ID
   */
  userId?: string;
  /**
   * Filter messages from this date
   */
  dateFrom?: string;
  /**
   * Filter messages until this date
   */
  dateTo?: string;
  /**
   * Cursor for pagination (format: createdAt_id)
   */
  cursor?: string;
  /**
   * Number of items per page
   */
  limit?: number;
};
