/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import type { MessageResponseDto } from './messageResponseDto';

export interface PaginatedMessagesResponseDto {
  items: MessageResponseDto[];
  nextCursor: string | null;
  hasMore: boolean;
}
