/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */

export interface UserResponseDto {
  id: string;
  username: string;
  email: string;
  createdAt: string;
  updatedAt: string;
}
