/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */

export type UserControllerSearchParams = {
  /**
   * Search term to match against usernames
   */
  q?: string;
  /**
   * Maximum number of results to return
   */
  limit?: number;
};
