packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'

onlyBuiltDependencies:
  - '@swc/core'
  - argon2
  - esbuild
  - msw
  - sharp
  - unrs-resolver
