/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { HealthResponseDto } from '../model';

import { fetchInstance } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const healthControllerCheck = (
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<HealthResponseDto>({ url: `/health`, method: 'GET', signal }, options);
};

export const getHealthControllerCheckQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthControllerCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheck>>> = ({ signal }) =>
    healthControllerCheck(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerCheck>>
>;
export type HealthControllerCheckQueryError = void;

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheck>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheck>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Health check
 */

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthControllerCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
