/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

/**
 * @summary Health check
 */
export type healthControllerCheckResponse200 = {
  data: void;
  status: 200;
};

export type healthControllerCheckResponse503 = {
  data: void;
  status: 503;
};

export type healthControllerCheckResponseSuccess = healthControllerCheckResponse200 & {
  headers: Headers;
};
export type healthControllerCheckResponseError = healthControllerCheckResponse503 & {
  headers: Headers;
};

export type healthControllerCheckResponse =
  | healthControllerCheckResponseSuccess
  | healthControllerCheckResponseError;

export const getHealthControllerCheckUrl = () => {
  return `/health`;
};

export const healthControllerCheck = async (
  options?: RequestInit,
): Promise<healthControllerCheckResponse> => {
  const res = await fetch(getHealthControllerCheckUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthControllerCheckResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as healthControllerCheckResponse;
};

export const getHealthControllerCheckQueryKey = () => {
  return [`/health`] as const;
};

export const getHealthControllerCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheck>>> = ({ signal }) =>
    healthControllerCheck({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthControllerCheck>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthControllerCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthControllerCheck>>
>;
export type HealthControllerCheckQueryError = void;

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheck>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthControllerCheck>>,
          TError,
          Awaited<ReturnType<typeof healthControllerCheck>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Health check
 */

export function useHealthControllerCheck<
  TData = Awaited<ReturnType<typeof healthControllerCheck>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getHealthControllerCheckQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
