/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateMessageDto, MessageControllerFindAllParams, UpdateMessageDto } from '../model';

export type messageControllerFindAllResponse200 = {
  data: void;
  status: 200;
};

export type messageControllerFindAllResponseSuccess = messageControllerFindAllResponse200 & {
  headers: Headers;
};
export type messageControllerFindAllResponse = messageControllerFindAllResponseSuccess;

export const getMessageControllerFindAllUrl = (params?: MessageControllerFindAllParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/messages?${stringifiedParams}` : `/messages`;
};

export const messageControllerFindAll = async (
  params?: MessageControllerFindAllParams,
  options?: RequestInit,
): Promise<messageControllerFindAllResponse> => {
  const res = await fetch(getMessageControllerFindAllUrl(params), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: messageControllerFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as messageControllerFindAllResponse;
};

export const getMessageControllerFindAllQueryKey = (params?: MessageControllerFindAllParams) => {
  return [`/messages`, ...(params ? [params] : [])] as const;
};

export const getMessageControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMessageControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof messageControllerFindAll>>> = ({
    signal,
  }) => messageControllerFindAll(params, { signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof messageControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MessageControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerFindAll>>
>;
export type MessageControllerFindAllQueryError = unknown;

export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | MessageControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof messageControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof messageControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof messageControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof messageControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMessageControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type messageControllerCreateResponse201 = {
  data: void;
  status: 201;
};

export type messageControllerCreateResponseSuccess = messageControllerCreateResponse201 & {
  headers: Headers;
};
export type messageControllerCreateResponse = messageControllerCreateResponseSuccess;

export const getMessageControllerCreateUrl = () => {
  return `/messages`;
};

export const messageControllerCreate = async (
  createMessageDto: CreateMessageDto,
  options?: RequestInit,
): Promise<messageControllerCreateResponse> => {
  const res = await fetch(getMessageControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createMessageDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: messageControllerCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as messageControllerCreateResponse;
};

export const getMessageControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof messageControllerCreate>>,
    TError,
    { data: CreateMessageDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof messageControllerCreate>>,
  TError,
  { data: CreateMessageDto },
  TContext
> => {
  const mutationKey = ['messageControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof messageControllerCreate>>,
    { data: CreateMessageDto }
  > = (props) => {
    const { data } = props ?? {};

    return messageControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MessageControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerCreate>>
>;
export type MessageControllerCreateMutationBody = CreateMessageDto;
export type MessageControllerCreateMutationError = unknown;

export const useMessageControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof messageControllerCreate>>,
      TError,
      { data: CreateMessageDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof messageControllerCreate>>,
  TError,
  { data: CreateMessageDto },
  TContext
> => {
  return useMutation(getMessageControllerCreateMutationOptions(options), queryClient);
};
export type messageControllerUpdateResponse200 = {
  data: void;
  status: 200;
};

export type messageControllerUpdateResponseSuccess = messageControllerUpdateResponse200 & {
  headers: Headers;
};
export type messageControllerUpdateResponse = messageControllerUpdateResponseSuccess;

export const getMessageControllerUpdateUrl = (id: string) => {
  return `/messages/${id}`;
};

export const messageControllerUpdate = async (
  id: string,
  updateMessageDto: UpdateMessageDto,
  options?: RequestInit,
): Promise<messageControllerUpdateResponse> => {
  const res = await fetch(getMessageControllerUpdateUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateMessageDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: messageControllerUpdateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as messageControllerUpdateResponse;
};

export const getMessageControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof messageControllerUpdate>>,
    TError,
    { id: string; data: UpdateMessageDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof messageControllerUpdate>>,
  TError,
  { id: string; data: UpdateMessageDto },
  TContext
> => {
  const mutationKey = ['messageControllerUpdate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof messageControllerUpdate>>,
    { id: string; data: UpdateMessageDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return messageControllerUpdate(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MessageControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerUpdate>>
>;
export type MessageControllerUpdateMutationBody = UpdateMessageDto;
export type MessageControllerUpdateMutationError = unknown;

export const useMessageControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof messageControllerUpdate>>,
      TError,
      { id: string; data: UpdateMessageDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof messageControllerUpdate>>,
  TError,
  { id: string; data: UpdateMessageDto },
  TContext
> => {
  return useMutation(getMessageControllerUpdateMutationOptions(options), queryClient);
};
export type messageControllerDeleteResponse204 = {
  data: void;
  status: 204;
};

export type messageControllerDeleteResponseSuccess = messageControllerDeleteResponse204 & {
  headers: Headers;
};
export type messageControllerDeleteResponse = messageControllerDeleteResponseSuccess;

export const getMessageControllerDeleteUrl = (id: string) => {
  return `/messages/${id}`;
};

export const messageControllerDelete = async (
  id: string,
  options?: RequestInit,
): Promise<messageControllerDeleteResponse> => {
  const res = await fetch(getMessageControllerDeleteUrl(id), {
    ...options,
    method: 'DELETE',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: messageControllerDeleteResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as messageControllerDeleteResponse;
};

export const getMessageControllerDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof messageControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof messageControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['messageControllerDelete'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof messageControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return messageControllerDelete(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MessageControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerDelete>>
>;

export type MessageControllerDeleteMutationError = unknown;

export const useMessageControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof messageControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof messageControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getMessageControllerDeleteMutationOptions(options), queryClient);
};
