/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateMessageDto,
  MessageControllerFindAllParams,
  MessageResponseDto,
  PaginatedMessagesResponseDto,
  UpdateMessageDto,
} from '../model';

import { fetchInstance } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const messageControllerFindAll = (
  params?: MessageControllerFindAllParams,
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<PaginatedMessagesResponseDto>(
    { url: `/messages`, method: 'GET', params, signal },
    options,
  );
};

export const getMessageControllerFindAllQueryKey = (params?: MessageControllerFindAllParams) => {
  return [`/messages`, ...(params ? [params] : [])] as const;
};

export const getMessageControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getMessageControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof messageControllerFindAll>>> = ({
    signal,
  }) => messageControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof messageControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type MessageControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerFindAll>>
>;
export type MessageControllerFindAllQueryError = unknown;

export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | MessageControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof messageControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof messageControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof messageControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof messageControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useMessageControllerFindAll<
  TData = Awaited<ReturnType<typeof messageControllerFindAll>>,
  TError = unknown,
>(
  params?: MessageControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof messageControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getMessageControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const messageControllerCreate = (
  createMessageDto: CreateMessageDto,
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<MessageResponseDto>(
    {
      url: `/messages`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createMessageDto,
      signal,
    },
    options,
  );
};

export const getMessageControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof messageControllerCreate>>,
    TError,
    { data: CreateMessageDto },
    TContext
  >;
  request?: SecondParameter<typeof fetchInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof messageControllerCreate>>,
  TError,
  { data: CreateMessageDto },
  TContext
> => {
  const mutationKey = ['messageControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof messageControllerCreate>>,
    { data: CreateMessageDto }
  > = (props) => {
    const { data } = props ?? {};

    return messageControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MessageControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerCreate>>
>;
export type MessageControllerCreateMutationBody = CreateMessageDto;
export type MessageControllerCreateMutationError = unknown;

export const useMessageControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof messageControllerCreate>>,
      TError,
      { data: CreateMessageDto },
      TContext
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof messageControllerCreate>>,
  TError,
  { data: CreateMessageDto },
  TContext
> => {
  return useMutation(getMessageControllerCreateMutationOptions(options), queryClient);
};
export const messageControllerUpdate = (
  id: string,
  updateMessageDto: UpdateMessageDto,
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<MessageResponseDto>(
    {
      url: `/messages/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateMessageDto,
      signal,
    },
    options,
  );
};

export const getMessageControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof messageControllerUpdate>>,
    TError,
    { id: string; data: UpdateMessageDto },
    TContext
  >;
  request?: SecondParameter<typeof fetchInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof messageControllerUpdate>>,
  TError,
  { id: string; data: UpdateMessageDto },
  TContext
> => {
  const mutationKey = ['messageControllerUpdate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof messageControllerUpdate>>,
    { id: string; data: UpdateMessageDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return messageControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MessageControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerUpdate>>
>;
export type MessageControllerUpdateMutationBody = UpdateMessageDto;
export type MessageControllerUpdateMutationError = unknown;

export const useMessageControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof messageControllerUpdate>>,
      TError,
      { id: string; data: UpdateMessageDto },
      TContext
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof messageControllerUpdate>>,
  TError,
  { id: string; data: UpdateMessageDto },
  TContext
> => {
  return useMutation(getMessageControllerUpdateMutationOptions(options), queryClient);
};
export const messageControllerDelete = (
  id: string,
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<void>({ url: `/messages/${id}`, method: 'DELETE', signal }, options);
};

export const getMessageControllerDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof messageControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof fetchInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof messageControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['messageControllerDelete'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof messageControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return messageControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type MessageControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof messageControllerDelete>>
>;

export type MessageControllerDeleteMutationError = unknown;

export const useMessageControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof messageControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof messageControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getMessageControllerDeleteMutationOptions(options), queryClient);
};
