/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { UserControllerSearchParams, UserResponseDto, UserSearchResultDto } from '../model';

import { fetchInstance } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Search users by username
 */
export const userControllerSearch = (
  params?: UserControllerSearchParams,
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<UserSearchResultDto[]>(
    { url: `/users/search`, method: 'GET', params, signal },
    options,
  );
};

export const getUserControllerSearchQueryKey = (params?: UserControllerSearchParams) => {
  return [`/users/search`, ...(params ? [params] : [])] as const;
};

export const getUserControllerSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerSearch>>,
  TError = void,
>(
  params?: UserControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerSearch>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerSearch>>> = ({ signal }) =>
    userControllerSearch(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerSearch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerSearch>>
>;
export type UserControllerSearchQueryError = void;

export function useUserControllerSearch<
  TData = Awaited<ReturnType<typeof userControllerSearch>>,
  TError = void,
>(
  params: undefined | UserControllerSearchParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerSearch>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof userControllerSearch>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerSearch<
  TData = Awaited<ReturnType<typeof userControllerSearch>>,
  TError = void,
>(
  params?: UserControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerSearch>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof userControllerSearch>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerSearch<
  TData = Awaited<ReturnType<typeof userControllerSearch>>,
  TError = void,
>(
  params?: UserControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerSearch>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Search users by username
 */

export function useUserControllerSearch<
  TData = Awaited<ReturnType<typeof userControllerSearch>>,
  TError = void,
>(
  params?: UserControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerSearch>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get current authenticated user profile
 */
export const userControllerMe = (
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<UserResponseDto>({ url: `/users/me`, method: 'GET', signal }, options);
};

export const getUserControllerMeQueryKey = () => {
  return [`/users/me`] as const;
};

export const getUserControllerMeQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>>;
  request?: SecondParameter<typeof fetchInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerMe>>> = ({ signal }) =>
    userControllerMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerMe>>>;
export type UserControllerMeQueryError = void;

export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerMe>>,
          TError,
          Awaited<ReturnType<typeof userControllerMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerMe>>,
          TError,
          Awaited<ReturnType<typeof userControllerMe>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>>;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get current authenticated user profile
 */

export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>>;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
