/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { UserResponseDto } from '../model';

/**
 * @summary Get current authenticated user profile
 */
export type userControllerMeResponse200 = {
  data: UserResponseDto;
  status: 200;
};

export type userControllerMeResponse401 = {
  data: void;
  status: 401;
};

export type userControllerMeResponseSuccess = userControllerMeResponse200 & {
  headers: Headers;
};
export type userControllerMeResponseError = userControllerMeResponse401 & {
  headers: Headers;
};

export type userControllerMeResponse =
  | userControllerMeResponseSuccess
  | userControllerMeResponseError;

export const getUserControllerMeUrl = () => {
  return `/users/me`;
};

export const userControllerMe = async (
  options?: RequestInit,
): Promise<userControllerMeResponse> => {
  const res = await fetch(getUserControllerMeUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: userControllerMeResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as userControllerMeResponse;
};

export const getUserControllerMeQueryKey = () => {
  return [`/users/me`] as const;
};

export const getUserControllerMeQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerMe>>> = ({ signal }) =>
    userControllerMe({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerMeQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerMe>>>;
export type UserControllerMeQueryError = void;

export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerMe>>,
          TError,
          Awaited<ReturnType<typeof userControllerMe>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerMe>>,
          TError,
          Awaited<ReturnType<typeof userControllerMe>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get current authenticated user profile
 */

export function useUserControllerMe<
  TData = Awaited<ReturnType<typeof userControllerMe>>,
  TError = void,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof userControllerMe>>, TError, TData>>;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
