/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateTagDto, TagResponseDto } from '../model';

export type tagControllerFindAllResponse200 = {
  data: TagResponseDto[];
  status: 200;
};

export type tagControllerFindAllResponseSuccess = tagControllerFindAllResponse200 & {
  headers: Headers;
};
export type tagControllerFindAllResponse = tagControllerFindAllResponseSuccess;

export const getTagControllerFindAllUrl = () => {
  return `/tags`;
};

export const tagControllerFindAll = async (
  options?: RequestInit,
): Promise<tagControllerFindAllResponse> => {
  const res = await fetch(getTagControllerFindAllUrl(), {
    ...options,
    method: 'GET',
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tagControllerFindAllResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as tagControllerFindAllResponse;
};

export const getTagControllerFindAllQueryKey = () => {
  return [`/tags`] as const;
};

export const getTagControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>>;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTagControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tagControllerFindAll>>> = ({ signal }) =>
    tagControllerFindAll({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tagControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TagControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof tagControllerFindAll>>
>;
export type TagControllerFindAllQueryError = unknown;

export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tagControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tagControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tagControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tagControllerFindAll>>
        >,
        'initialData'
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTagControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export type tagControllerCreateResponse201 = {
  data: TagResponseDto;
  status: 201;
};

export type tagControllerCreateResponseSuccess = tagControllerCreateResponse201 & {
  headers: Headers;
};
export type tagControllerCreateResponse = tagControllerCreateResponseSuccess;

export const getTagControllerCreateUrl = () => {
  return `/tags`;
};

export const tagControllerCreate = async (
  createTagDto: CreateTagDto,
  options?: RequestInit,
): Promise<tagControllerCreateResponse> => {
  const res = await fetch(getTagControllerCreateUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTagDto),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tagControllerCreateResponse['data'] = body ? JSON.parse(body) : {};
  return { data, status: res.status, headers: res.headers } as tagControllerCreateResponse;
};

export const getTagControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tagControllerCreate>>,
    TError,
    { data: CreateTagDto },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tagControllerCreate>>,
  TError,
  { data: CreateTagDto },
  TContext
> => {
  const mutationKey = ['tagControllerCreate'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tagControllerCreate>>,
    { data: CreateTagDto }
  > = (props) => {
    const { data } = props ?? {};

    return tagControllerCreate(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TagControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tagControllerCreate>>
>;
export type TagControllerCreateMutationBody = CreateTagDto;
export type TagControllerCreateMutationError = unknown;

export const useTagControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tagControllerCreate>>,
      TError,
      { data: CreateTagDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tagControllerCreate>>,
  TError,
  { data: CreateTagDto },
  TContext
> => {
  return useMutation(getTagControllerCreateMutationOptions(options), queryClient);
};
