/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Future Media Challenge API
 * The API for the Future Media Challenge application
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { CreateTagDto, TagResponseDto } from '../model';

import { fetchInstance } from '../../lib/api-client';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const tagControllerFindAll = (
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<TagResponseDto[]>({ url: `/tags`, method: 'GET', signal }, options);
};

export const getTagControllerFindAllQueryKey = () => {
  return [`/tags`] as const;
};

export const getTagControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>>;
  request?: SecondParameter<typeof fetchInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTagControllerFindAllQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof tagControllerFindAll>>> = ({ signal }) =>
    tagControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tagControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TagControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof tagControllerFindAll>>
>;
export type TagControllerFindAllQueryError = unknown;

export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tagControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tagControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tagControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tagControllerFindAll>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTagControllerFindAll<
  TData = Awaited<ReturnType<typeof tagControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof tagControllerFindAll>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTagControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const tagControllerCreate = (
  createTagDto: CreateTagDto,
  options?: SecondParameter<typeof fetchInstance>,
  signal?: AbortSignal,
) => {
  return fetchInstance<TagResponseDto>(
    {
      url: `/tags`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTagDto,
      signal,
    },
    options,
  );
};

export const getTagControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tagControllerCreate>>,
    TError,
    { data: CreateTagDto },
    TContext
  >;
  request?: SecondParameter<typeof fetchInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tagControllerCreate>>,
  TError,
  { data: CreateTagDto },
  TContext
> => {
  const mutationKey = ['tagControllerCreate'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tagControllerCreate>>,
    { data: CreateTagDto }
  > = (props) => {
    const { data } = props ?? {};

    return tagControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TagControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tagControllerCreate>>
>;
export type TagControllerCreateMutationBody = CreateTagDto;
export type TagControllerCreateMutationError = unknown;

export const useTagControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tagControllerCreate>>,
      TError,
      { data: CreateTagDto },
      TContext
    >;
    request?: SecondParameter<typeof fetchInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tagControllerCreate>>,
  TError,
  { data: CreateTagDto },
  TContext
> => {
  return useMutation(getTagControllerCreateMutationOptions(options), queryClient);
};
